## Basic Configuration
baseurl = "/MADDVIPR/"
languageCode = "en"

title = "MADDVIPR"
theme = "terrassa"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

# summarylength = 30

#paginate = 5


## Social Accounts
[params.social]
    #github = "<username>"
    #instagram = "<username>"
    #xing = "<username>"
    #linkedin = "<username>"
    #twitter = "<username>"
    #facebook = "<username>"
    #stackoverflow = "<username>"
    #telegram = "<username>"
    #email = "your-email@example.com"
    # gravatar = "your-email@example.com"

## Main Menu
[[menu.main]]
    name = "Blog"
    weight = 200
    identifier = "posts"
    url = "/posts/"

[[menu.main]]
    name = "References"
    weight = 250
    identifier = "state"
    url = "/state/"
[[menu.main]]
    name = "People"
    identifier = "contact"
    weight = 300
    url = "/contact/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 100
    url = "/about/"
